#!/bin/sh
for name in target/*/WEB-INF/lib/*.jar ; do
  CP=$CP:$name
done

if [ "$1" == "-debug" ] ; then
    DEBUG_OPTS="-J-Xdebug -J-Xnoagent -J-Djava.compiler=NONE -J-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"
fi

scala $DEBUG_OPTS -cp $CP -J-XX:MaxPermSize=512m -J-Xmx2048m -Yrepl-sync 

